apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: mongodb
    project: roboshop

spec:
  replicas: 1
  selector:
    MatchLabels:
      app: mongodb
       tier: mongodb
       project: roboshop
  template:
    metadata:
      labels:
        app: mongodb
        tier: mongodb
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: mongodb:1.0.0

---
apiVersion: v1 
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
    tier: mongodb
    project: roboshop
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP

    

  
